name: Claudio d'Angelis Homepage
src: .
url: http://www.claudiodangelis.com
description: Interested in computer programming and progressive rock sounds
version: 6.0
safe: false
port: 4000
destination: /srv/http/dawson/
paginate: 5
paginate_path: "/page:num"
highlighter: true
permalink: /:year/:title/
markdown: kramdown
excerpt_separator: "<!--more-->"
gems: [jekyll-paginate]
